# Numpy basics

## Numpy advantages
- Vectorization. No need to write ugly nested for loops to loop through each dimension; use of the same mathematical notation of linear algebr
- C-like speed and efficiency, since the backend libraries that performs the operations are written in C
- Vastly used for scientific computing
- Most of the ndarray class methods are mirrored in the outer-most numpy namespace (np), so you can call functions from the np package or from the ndarray object.

How numpy arrays are different from python lists, besides numeric computation speed and efficiency? 
1. Numpy arrays are homogeneous, all elements are of the same type
2. They have shape! Python lists are flat (if you don't use nested lists)
3. You can perform operations that are not possible with python lists

## Basic concepts
- The core construct of numpy is the ndarray object; you can istantiate one using the ndarray constructor, or the np.array() function
- A ndarray object is composed of uniform elements (all floats, all integers, all complex, etc) and has a SHAPE (indicates if the element is a vector, matrix, tensor, etc)
- The ndarray object has various attributes, like ndim (tells the number of dimension, in numpy called AXIS) of the ndarray; shape attribute, that is a tuple indicating the number of elements for each dimension (for a vector the shape is (m,) for a matrix (m,n), for a 3D tensor (m,n,o), etc), the size (the total number of element, for ex mxn in a matrix), dtype (the type of the elements in the ndarray), etc

In [2]:
import numpy as np

# core of the numpy package is the ndarray object, multidimensional array
# You can use both the ndarray constructor or the array function to create an ndarray object
myarray = np.array([1, 2, 3, 4, 5])
print(f'myarray = \n{myarray}, type = {type(myarray)}')

print(f'ndim = {myarray.ndim}')             # number of dimensions (in numpy called axis)
print(f'shape = {myarray.shape}')           # tuple of integers indicating the size of the array in each dimension. (5,) means 1D array with 5 elements
print(f'size = {myarray.size}')
print(f'dtype = {myarray.dtype}')
print()

# create a 2D array (matrix). Notice that we basically pass a nested list to the array function
myarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(f'myarray = \n{myarray}')
print(f'ndim = {myarray.ndim}')
print(f'shape = {myarray.shape}')
print(f'size = {myarray.size}')
print(f'dtype = {myarray.dtype}')
print()

# Transpose of the previous matrix
myarr_traspose = myarray.T
print(f'myarr_traspose = \n{myarr_traspose}')
print(f'ndim = {myarr_traspose.ndim}')
print(f'shape = {myarr_traspose.shape}')
print(f'size = {myarr_traspose.size}')
print()

# You can specify the data type of the elements of the array
myarray = np.array([1, 2, 3, 4, 5], dtype=np.complex64)
print(f'myarray = \n{myarray}')
print(f'dtype = {myarray.dtype}')



myarray = 
[1 2 3 4 5], type = <class 'numpy.ndarray'>
ndim = 1
shape = (5,)
size = 5
dtype = int32

myarray = 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
ndim = 2
shape = (4, 3)
size = 12
dtype = int32

myarr_traspose = 
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
ndim = 2
shape = (3, 4)
size = 12

myarray = 
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
dtype = complex64


## Creating ndarray objects with np "helpers" functions
Often we don't know the data that we'll need to put inside an array or matrix, but we know the shape. Since "growing" an array is an expensive operation (ndarray are immutables! Inserting new elements or performing modifications, means to create a new object), it's good practice to istantiate the ndarray of the size/shape that we need using empty ndarrays, that contains zero, ones, identity matrix, etc

In [3]:
# You can create arrays with zeros, ones, or random values
myarray = np.zeros((3, 4))
print(f'myarray = {myarray}')
print()

myarray = np.ones((3, 4))
print(f'myarray = {myarray}')
print()

myarray = [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

myarray = [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]



## Arange and linspace
As for python list, you can create arrays of elements distributed in a specified bounded range of two integer numbers, with a certain integer stepsize, using the function arange (similar to python range built-in function).
If instead you need to generate still elements distributed in a bounded range (a,b) but a or b are float, or the step size is a float, or we only have the number of points we want to have in the range and not the stepsize, it's better to use the linspace numpy function.

In [4]:
# Syntax: arange(start, stop, step)
myarr = np.arange(0, 10, 2)
print(myarr)

# Syntax: linspace(start, stop, num_items)
myarr = np.linspace(0, 100, 7)
print(myarr)

# Linspace is useful to evaluate functions in a range of values
from numpy import pi
x = np.linspace(0, 2*pi, 100)
f = np.sin(x)
print(f)

[0 2 4 6 8]
[  0.          16.66666667  33.33333333  50.          66.66666667
  83.33333333 100.        ]
[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 

Riprendi da pagina 13 del pdf (manuale numpy)