In [1]:
# Some hints

## Alayws specify the type of vector (colum or row)


In [2]:
import numpy as np

vect = np.array([1, 2, 3])
vect.shape

vect_col = vect.reshape(-1, 1)
vect_row = vect.reshape(1, -1)

print(f'Column vector, shape {vect_col.shape}:\n {vect_col}\n')
print(f'Row vector, shape {vect_row.shape}:\n {vect_row}\n')
print(f'Transpose of the column vector:\n {vect_col.T}\n')
print(f'Transpose of the row vector:\n {vect_row.T}\n')



Column vector, shape (3, 1):
 [[1]
 [2]
 [3]]

Row vector, shape (1, 3):
 [[1 2 3]]

Transpose of the column vector:
 [[1 2 3]]

Transpose of the row vector:
 [[1]
 [2]
 [3]]

